version: '3.8'

services:
  backend:
    build: .
    container_name: backend-ecommerce
    ports:
      - "3001:3000" # <-- Cambio: escucha en el puerto 3001 afuera
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/Project01
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

